### ISSUE TITLE
Add functionality to set K/V pairs in st2 datastore

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#108]
Similar to [Pack Install #74](https://github.com/StackStorm/ansible-st2/issues/74) we'll need an abstraction for `st2` key/value store.

For example define a list of K/V pairs in `yaml` which will be added in https://docs.stackstorm.com/datastore.html during Ansible provisioning.

**Comment by johnarnold** [comment]
Current workaround:

```
---
- name: set path vars for datastore keys
  set_fact:
    st2_keys_path: /etc/st2/st2_keys.json
    st2_keys_imported_path: /etc/st2/st2_keys.touch

- name: load datastore vars from file
  include_vars:
    file: st2_keys.yml

- name: Check if keys imported file exists
  stat:
    path: "{{st2_keys_imported_path}}"
  register: keys_exist
  become: true

- name: Write key file
  copy:
    content: "{{st2_keys | to_json}}"
    dest: "{{st2_keys_path}}"
  when: keys_exist.stat.exists == False
  become: true

- name: Import Keys
  become: true
  shell: "st2 key load {{st2_keys_path}} && rm -f {{st2_keys_path}} && touch {{st2_keys_imported_path}}"
  args:
    creates: "{{st2_keys_imported_path}}"
  when: keys_exist.stat.exists == False
```
