### ISSUE TITLE
st2chatops smoke test fails on latest vagrant

### ISSUE THREAD

**Issue by galtenberg** [StackStorm/ansible-st2#145]
From a clean clone and `vagrant up` on `Vagrant 1.9.4`:

```
...
TASK [st2smoketests : Verify st2chatops using bin/hubot] ***********************
 [WARNING]: when statements should not include jinja2 templating delimiters
such as {{ }} or {% %}. Found: '{{ st2chatops_hubot_adapter|title }} client now
connected' not in test_output.stdout or 'DEBUG Added command: st2 list' not in
test_output.stdout

fatal: [ubuntu16]: FAILED! => {"changed": false, "cmd": ["timeout", "25", "bin/hubot"], "delta": "0:00:00.663364", "end": "2017-05-13 04:38:56.530698", "failed": true, "failed_when_result": true, "rc": 0, "start": "2017-05-13 04:38:55.867334", "stderr": "", "stderr_lines": [], "stdout": "[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading adapter shell\n\u001b[1G\u001b[0Jhubot> \u001b[8G[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading scripts from /opt/stackstorm/chatops/scripts\n[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading scripts from /opt/stackstorm/chatops/src/scripts\n[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading hubot-scripts from /opt/stackstorm/chatops/node_modules/hubot-scripts/src/scripts\n[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.\n\nYour hubot-scripts.json is empty, so you just need to remove it.", "stdout_lines": ["[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading adapter shell", "\u001b[1G\u001b[0Jhubot> \u001b[8G[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading scripts from /opt/stackstorm/chatops/scripts", "[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading scripts from /opt/stackstorm/chatops/src/scripts", "[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] DEBUG Loading hubot-scripts from /opt/stackstorm/chatops/node_modules/hubot-scripts/src/scripts", "[Sat May 13 2017 04:38:56 GMT+0000 (UTC)] WARNING Loading scripts from hubot-scripts.json is deprecated and will be removed in 3.0 (https://github.com/github/hubot-scripts/issues/1113) in favor of packages for each script.", "", "Your hubot-scripts.json is empty, so you just need to remove it."]}
	to retry, use: --limit @/vagrant/stackstorm.retry

PLAY RECAP *********************************************************************
ubuntu16                   : ok=82   changed=56   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

$ vagrant --version
Vagrant 1.9.4
```

**Comment by armab** [comment]
Thanks for the report.

Did you configure any adapter via `st2chatops` role?
I suspect that's the issue you're experiencing. Please check ^^.

For example, to make it working with `slack` adapter you'll need something like this:
```yaml
    - name: Install st2chatops with "slack" hubot adapter
      role: st2chatops
      vars:
        st2chatops_version: latest
        st2chatops_st2_api_key: CHANGE-ME-PLEASE # (optional) This can be generated using "st2 apikey create -k"
        st2chatops_hubot_adapter: slack
        st2chatops_config:
          HUBOT_SLACK_TOKEN: xoxb-CHANGE-ME-PLEASE
```
from the https://docs.stackstorm.com/latest/install/ansible.html#example-play

See variables for `st2chatops` role: https://github.com/stackstorm/ansible-st2#variables

----

I think it's our fail with Ansible messaging and documentation to make it explicitly clear to user that `st2chatops` configuration is required.
