### ISSUE TITLE
Feature Request: configure datastore secret encryption key

### ISSUE THREAD

**Issue by johnarnold** [StackStorm/ansible-st2#153]
See: https://docs.stackstorm.com/datastore.html#securing-secrets-admin-only

**Comment by johnarnold** [comment]
As an example, I made a roles/st2/tasks/datastore.yml:

```
---
- name: set path vars for datastore keys
  set_fact:
    st2_keys_path: /etc/st2/st2_keys.json
    st2_keys_imported_path: /etc/st2/st2_keys.touch

- name: load datastore vars from file
  include_vars:
    file: st2_keys.yml

- name: Check if keys imported file exists
  stat:
    path: "{{st2_keys_imported_path}}"
  register: keys_exist
  become: true

- name: Write key file
  copy:
    content: "{{st2_keys | to_json}}"
    dest: "{{st2_keys_path}}"
  when: keys_exist.stat.exists == False
  become: true

- name: Import Keys
  become: true
  shell: "st2 key load {{st2_keys_path}} && rm -f {{st2_keys_path}} && touch {{st2_keys_imported_path}}"
  args:
    creates: "{{st2_keys_imported_path}}"
  when: keys_exist.stat.exists == False
```

Unfortunately it fails right now as I don't have an auth token at deployment time.
