### ISSUE TITLE
st2chatops smoke tests fail when HUBOT_LOG_LEVEL=info

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/ansible-st2#170]
I have this st2chatops config:

```
st2chatops_hubot_adapter: slack
st2chatops_config:
  HUBOT_SLACK_TOKEN: "{{ theatro_vault_slack_bot_token }}"
  HUBOT_LOG_LEVEL: info
```

This forces the st2chatops smoketest to fail despite https://github.com/StackStorm/ansible-st2/blob/136a41ee82f9f2bf187a28b9336552b5918f238d/roles/st2smoketests/tasks/st2chatops.yml#L4-L8

This is because `bin/hubot` overwrites any variables that are already in the environment:

```
. $HERE/st2chatops.env
```

https://github.com/StackStorm/st2chatops/blob/9066a1fed83615fa13b19985c546e9621b612cc0/bin/hubot#L15
