### ISSUE TITLE
Pack Install

### ISSUE THREAD

**Issue by armab** [StackStorm/ansible-st2#74]
Ability to list st2 packs to install as well as provide configurations/settings for them.

https://docs.stackstorm.com/pack_configs.html

Alternative example: https://github.com/stackstorm/puppet-st2#installing-and-configuring-packs

**Comment by armab** [comment]
One of the possible syntaxes for the new interface with the pack install/configure: 

```yaml
st2_packs:
  # just `st2 pack install ansible`
  - name: ansible

  - name: aws
    # version pinning
    version: 1.2.3
    # state `present`/`absent`
    state: present
    # in-line config
    config:
      setup:
        region: "us-west-2"
        aws_access_key_id: ""
        aws_secret_access_key: ""
      interval: 20

  - name: github
    config:
      token: "abc123def"
      user: ""
      password: ""
      repository_sensor:
        repositories:
          - user: StackStorm
            name: st2

   # alternative way to use already prepared file which will be
   # transferred to /opt/stackstorm/configs/servicenow.yml
  - name: servicenow
    config: files/configs/servicenow.yml

  # uninstall pack
  - name: consul
    state: absent
```
